# Generated by Django 5.1.2 on 2024-10-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("initiatives", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="initiative",
            options={"verbose_name": "Инициатива", "verbose_name_plural": "Инициативы"},
        ),
        migrations.AddField(
            model_name="initiative",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="initiatives/",
                verbose_name="Изображение инициативы",
            ),
        ),
    ]
