# Generated by Django 5.1.2 on 2024-10-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("initiatives", "0003_initiative_votes"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "На проверке"),
                    ("approved", "Одобрено"),
                    ("rejected", "Отклонено"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
