# Generated by Django 5.1.2 on 2024-10-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("initiatives", "0004_initiative_status"),
        ("initiatives", "0005_create_moderator_group"),
    ]

    operations = []
