# Generated by Django 5.1.2 on 2024-11-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "initiatives",
            "0010_initiative_initiator_alter_initiative_description_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="initiative",
            old_name="initiator",
            new_name="user",
        ),
    ]
