# Generated by Django 5.1.2 on 2024-11-05 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("initiatives", "0011_rename_initiator_initiative_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="rejection_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Причина отказа"
            ),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="initiatives",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
