# Generated by Django 5.1.2 on 2024-11-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("initiatives", "0012_initiative_rejection_reason_alter_initiative_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="initiative",
            name="rejection_reason",
        ),
        migrations.AddField(
            model_name="initiative",
            name="moderator_comment",
            field=models.TextField(
                blank=True,
                default="нет",
                null=True,
                verbose_name="Комментарий модератора",
            ),
        ),
    ]
