# Generated by Django 5.1.2 on 2024-11-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("initiatives", "0013_remove_initiative_rejection_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="winner_month",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Победивший месяц"
            ),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "На проверке"),
                    ("approved", "Одобрено"),
                    ("rejected", "Отклонено"),
                    ("winner", "Победитель"),
                    ("inactive", "Неактивно"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
