# Generated by Django 5.1.2 on 2024-11-06 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("initiatives", "0014_initiative_winner_month_alter_initiative_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="initiative",
            name="image",
        ),
        migrations.CreateModel(
            name="InitiativeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="initiatives/images/"
                    ),
                ),
                (
                    "initiative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="initiatives.initiative",
                    ),
                ),
            ],
        ),
    ]
