# Generated by Django 5.1.2 on 2024-11-09 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("initiatives", "0015_remove_initiative_image_initiativeimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="initiativeimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="initiatives/"),
        ),
        migrations.CreateModel(
            name="Update",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "initiative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="initiatives.initiative",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UpdateImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="updates/")),
                (
                    "update",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="initiatives.update",
                    ),
                ),
            ],
        ),
    ]
